### ISSUE TITLE
How to process JRDB dataset

### ISSUE THREAD

**Issue by Anthonyjlem** [ldtho/PiFeNet#3]
Hello,

I want to run PiFeNet on the JRDB dataset, but I am running into an error when I run create_data.py:

~~~shell
(pifenet) anthony@galapagos:~/Documents/PiFeNet/second$ python create_data.py jrdb22_data_prep --root_path=/home/anthony/Documents/JRDB
[Warning] Since Open3D 0.15, installing Open3D via conda is deprecated. Please re-install Open3D via: `pip install open3d -U`./home/anthony/Documents/PiFeNet/second/data/ImageSets_jrdb22/train.txt
/home/anthony/Documents/PiFeNet/second/data/ImageSets_jrdb22/val.txt
Generate info. this may take several minutes.Traceback (most recent call last):
  File "create_data.py", line 37, in <module>
    fire.Fire()  File "/home/anthony/anaconda3/envs/pifenet/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/anthony/anaconda3/envs/pifenet/lib/python3.8/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/anthony/anaconda3/envs/pifenet/lib/python3.8/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "create_data.py", line 24, in jrdb22_data_prep
    kitti_ds.create_kitti_info_file(root_path, dataset='jrdb22', calib=False)
  File "/home/anthony/Documents/PiFeNet/second/data/kitti_dataset.py", line 385, in create_kitti_info_file
    kitti_infos_train = kitti.get_kitti_image_info(
  File "/home/anthony/Documents/PiFeNet/second/data/kitti_common.py", line 284, in get_kitti_image_info
    return list(image_infos)
  File "/home/anthony/anaconda3/envs/pifenet/lib/python3.8/concurrent/futures/_base.py", line 611, in result_iterator
    yield fs.pop().result()
  File "/home/anthony/anaconda3/envs/pifenet/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/home/anthony/anaconda3/envs/pifenet/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/home/anthony/anaconda3/envs/pifenet/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/anthony/Documents/PiFeNet/second/data/kitti_common.py", line 210, in map_func
    pc_info['velodyne_path'] = get_velodyne_path(
  File "/home/anthony/Documents/PiFeNet/second/data/kitti_common.py", line 116, in get_velodyne_path
    return get_kitti_info_path(idx, prefix, 'velodyne', tail, training,
  File "/home/anthony/Documents/PiFeNet/second/data/kitti_common.py", line 97, in get_kitti_info_path
    raise ValueError("file not exist: {}".format(file_path))
ValueError: file not exist: training/velodyne/000000.bin
~~~

I set up my folder directory following the README. Should I rename my "train_dataset_with_activity" directory to "training"? Which velodyne is the code looking for (the upper or lower)? And why is the code looking for a bin file when the JRDB dataset provides pcd files?

Thank you.

**Comment by ldtho** [comment]
I guess you haven't converted the dataset to KITTI format
You can do it by running the [convert_dataset_to_KITTI.py](https://github.com/JRDB-dataset/jrdb_toolkit/blob/main/detection_eval/convert_dataset_to_KITTI.py) from the JRDB_toolkit repo
sample syntax:
python detection_eval/convert_dataset_to_KITTI.py -i /path/to/JRDB2022 -o /new/path/to/JRDB22_converted

**Comment by Anthonyjlem** [comment]
Thanks!
